### ISSUE TITLE
IllegalStateException when scrolling in the example app

### ISSUE THREAD

**Issue by Plastix** [Genius/groupie#21]
```
W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame.
                java.lang.IllegalStateException: 
                    at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2403)
                    at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:4634)
                    at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:10472)
                    at android.support.v7.widget.RecyclerView$Adapter.notifyItemInserted(RecyclerView.java:6214)
                    at com.genius.groupie.GroupAdapter.onItemInserted(GroupAdapter.java:204)
                    at com.genius.groupie.NestedGroup.notifyItemInserted(NestedGroup.java:195)
                    at com.genius.groupie.Section.notifyItemInserted(Section.java:205)
                    at com.genius.groupie.Section.add(Section.java:53)
                    at com.genius.groupie.example.MainActivity$1.onLoadMore(MainActivity.java:88)
                    at com.genius.groupie.example.InfiniteScrollListener.onScrolled(InfiniteScrollListener.java:41)
                    at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4305)
                    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4463)
                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                    at android.view.Choreographer.doFrame(Choreographer.java:603)
                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                    at android.os.Handler.handleCallback(Handler.java:739)
                    at android.os.Handler.dispatchMessage(Handler.java:95)
                    at android.os.Looper.loop(Looper.java:148)
                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                    at java.lang.reflect.Method.invoke(Native Method)
                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by lisawray** [comment]
note that this is not a fatal crash -- just a log.  in a production app, the data might get out of sync.
but, the fix is:

post the data change into a handler and do it there. (both the adapter change and the notification)

**Comment by Plastix** [comment]
Thanks for the explanation.

**Comment by lisawray** [comment]
I'll still fix it when i have time :)

**Comment by Plastix** [comment]
Let me know if that PR is the fix you were envisioning.
